#!/bin/bash

# install composer
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
chmod 755 /usr/bin/composer

# install vendor
cd /var/lib/small-scheduler
composer update
